FROM pablodejuan/docker_ipopt_combined

# Set the working directory to the home directory of the container
WORKDIR /home

# Set the PYTHONPATH environment variable
ENV PYTHONPATH=/home/colmenasrc:$PYTHONPATH

# Copy the 'src' folder from the host machine into the container's home directory
COPY colmenasrc/ /home/colmenasrc/
COPY andes/ /home/andes/

RUN python3 /home/colmenasrc/scripts/main_colmena.py
