FROM python:3.9.18-slim-bookworm

# Set working directory and copy project
COPY . /home
WORKDIR /home

# Install build and system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    git \
    wget \
    pkg-config \
    liblapack-dev \
    && apt-get clean

# Install your Python package (local)
RUN python3 -m pip install .

# Install build dependencies
RUN apt-get update && apt-get install -y \
    git \
    g++ \
    dos2unix \
    pkg-config \
    wget \
    make \
    tar \
    patch \
    build-essential \
    gfortran \
    && rm -rf /var/lib/apt/lists/*

# Clone coinbrew and build IPOPT
RUN git clone https://github.com/coin-or/coinbrew.git /coinbrew && \
    cd /coinbrew && \
    ./coinbrew fetch Ipopt@releases/3.14.12 --no-prompt && \
    ./coinbrew build Ipopt --no-prompt --prefix=/usr/local && \
    ./coinbrew install Ipopt --no-prompt && \
    rm -rf /coinbrew

# Optional: Add IPOPT binaries to PATH
ENV PATH="/usr/local/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/lib:"
ENTRYPOINT start

